inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'

Rails:
  Enabled: true

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 20

Layout/EndOfLine:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
